version: '3.1'

services:
    db:
        image: postgres
        restart: always
        ports:
            - "5433:5432"
        environment:
            POSTGRES_DB: "hw4"
            POSTGRES_USER: "user"
            POSTGRES_PASSWORD: "pass"

#    adminer:
#        image: adminer
#        restart: always
#        ports:
#            - "8089:8080"