version: '3.1'

services:
    db:
        container_name: db
        image: postgres
        restart: always
        ports:
            - "${DB_PORT}:5432"
        environment:
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASS}

#    adminer:
#        image: adminer
#        restart: always
#        ports:
#            - "8089:8080"